"""add workout models

Revision ID: 426683888ace
Revises: ce57b45d8b7e
Create Date: 2026-02-09 01:28:08.936881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426683888ace'
down_revision: Union[str, Sequence[str], None] = 'ce57b45d8b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_workouts_ended_after_started'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'order_index', name='uq_workout_exercises_workout_order')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.SMALLINT(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_lbs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('set_type', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('set_type IN (0, 1, 2)', name='ck_workout_sets_set_type'),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_exercise_id', 'set_number', name='uq_workout_sets_exercise_set_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    # ### end Alembic commands ###
