"""add uniqueness constraint

Revision ID: ce57b45d8b7e
Revises: 554e127a4559
Create Date: 2026-02-08 23:15:50.467257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce57b45d8b7e'
down_revision: Union[str, Sequence[str], None] = '554e127a4559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    # ### end Alembic commands ###
